# —— Chart Parameters ——
replicaCount: 1

serviceAccount:
  create: false
  name: ""

# —— Image settings ——
image:
  repository: demo-app
  tag: "v2"
  pullPolicy: IfNotPresent

# —— Service config ——
service:
  type: ClusterIP  # changeable to NodePort or LoadBalancer via values
  port: 8080

# Ingress 
ingress:
  enabled: true
  # Using k3s's built‑in Traefik, with host demo.local
  hosts:
    - host: demo.local
      paths:
        - path: /
          pathType: Prefix

# —— Resource Requests & Limits ——
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

# —— Autoscaling Stub (disabled by default) ——
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 75

config:
  appName: DemoApp
  logLevel: info

secret:
  dbPassword: securepassword
  apiToken: secrettoken

useSealedSecrets: true

admin:
  user: admin
  existingSecret: grafana-admin
  passwordKey: GF_SECURITY_ADMIN_PASSWORD

dashboardProviders:
  enabled: true
  config:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /opt/bitnami/grafana/dashboards/default

global:
  security:
    allowInsecureImages: true
    
persistence:
  enabled: true
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  size: 10Gi

grafana:
  dashboardFilename: "demo-app-dashboard.json"

