apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: demo-app-rules
  namespace: monitoring
  labels:
    release: prometheus
spec:
  groups:
    - name: demo-app.rules
      rules:
        - alert: DemoAppNoRequests
          expr: rate(http_request_total{job="demo-app"}[1m]) == 0
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "No HTTP requests to demo-app"
            description: "demo-app has received no requests in the last 1 minute."

        - alert: HighCPUUsage
          expr: rate(container_cpu_usage_seconds_total{namespace="project-c", pod=~"demo-app.*"}[1m]) > 0.05
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "High CPU usage detected in demo-app"
            description: "CPU usage for demo-app pods has exceeded 5% for 1 minute."

