# project-c/elasticsearch-values.yaml
replicas: 1
protocol: http

security:
  enabled: false

http:
  tls:
    enabled: false

transport:
  tls:
    enabled: false

extraEnvs:
  - name: xpack.security.enabled
    value: "false"
  - name: xpack.security.http.ssl.enabled
    value: "false"
  - name: xpack.security.transport.ssl.enabled
    value: "false"


