apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: logging
  labels:
    app: fluent-bit
spec:
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
    spec:
      serviceAccountName: fluent-bit

      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule

      containers:
        - name: fluent-bit
          image: fluent/fluent-bit:2.1.8  # or latest stable
          env:
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: containers
              mountPath: /var/log/containers
              readOnly: true
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: db
              mountPath: /var/log/db
            - name: config-dir
              mountPath: /fluent-bit/etc

      initContainers:
        - name: copy-config
          image: busybox:1.35
          command:
            - /bin/sh
            - -c
            - cp -R /tmp/config/. /fluent-bit/etc/
          volumeMounts:
            - name: config-map
              mountPath: /tmp/config
            - name: config-dir
              mountPath: /fluent-bit/etc

      terminationGracePeriodSeconds: 30

      volumes:
        - name: config-map
          configMap:
            name: fluent-bit-config

        - name: config-dir
          emptyDir: {}

        - name: varlog
          hostPath:
            path: /var/log

        - name: containers
          hostPath:
            path: /var/log/containers

        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers

        - name: db
          emptyDir: {}

