# project-c/grafana-values.yaml
ingress:
  enabled: true
  ingressClassName: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  hosts:
    - grafana.local
  paths:
    - /

admin:
  existingSecret: grafana-admin-credentials
  userKey: admin-user
  passwordKey: admin-password

sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
    folder: /opt/bitnami/grafana/provisioning/dashboards/custom
