# project-c/readonly.yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: project-c
  name: readonly
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: readonly-binding
  namespace: project-c
subjects:
- kind: ServiceAccount
  name: readonly-user
  namespace: project-c
roleRef:
  kind: Role
  name: readonly
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: readonly-user
  namespace: project-c
