# project-c/charts/demo-app/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: monitoring
  name: {{ include "demo-app.fullname" . }}-config
  labels:
    grafana_dashboard: "1"
    app.kubernetes.io/name: {{ include "demo-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
data:
{{- range .Values.grafana.dashboardFilenames }}
  {{ . }}: |
{{ $.Files.Get (printf "dashboards/%s" .) | indent 4 }}
{{- end }}

