# project-c/charts/demo-app/templates/prometheus-ingress.yaml
{{- if .Values.prometheus.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-ingress
  namespace: monitoring
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    {{- with .Values.prometheus.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  rules:
  - host: {{ .Values.prometheus.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.prometheus.ingress.serviceName }}
            port:
              number: {{ .Values.prometheus.ingress.servicePort }}
{{- end }}

