# project-c/charts/demo-app/templates/sealedsecret.yaml
{{- if .Values.useSealedSecrets }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgB4/KMGH5fFbZT/xTR9b1iasq1ZCBasPnDdc/BGxoSB4xzGO7iJj0EY48zlf1zt3ziqUMfF8JXtOFg0NJMmwON4AWYenlisww9QwfZzJ/fN/kfzhpL0y2KtyBoP7DdELLZ5e6DV9krMw04yWtAE0y1A+ZqnHWo5UTdUlThAyTYfeqWTobOXITlg+Xz2QAbPtXJMQLq5sTHt61HS/5Gig5l4YmkkZQYIGblnuX5BDHRrktFJGi/IYLet+2hRJXUx9A0SOWpk0DuCsravCIw1K8yG63TJ0R3Fc7eFoxnb23FYGvAR+/uphQi5tI4qhoNyF8Xb2VJA2bwAziBydBdQNxrJFExzJWr6wGGFztdkPAmaswBQH6Ll15LiKbPbROYoXpVmWdpkGbBNHpUmUGeRQD34FiqB1jN2efkZ/5CxXSVr0oZaf2ymAO8oAqNt7Pta+YTpobGIZwwEru1tRJ61pxsYu6IQ6fF7JMoGo31rZaT74eDDFfLGhSMrfB0TE9lmpyIwuTbGezApuAHTmoPkuLz0k29Os2IIZD7zKyAeVzGm52drPfSuJrGif4eNiZjGZj+3a/imjftUXdDe2cVt7LiYesxJGvLMm+LFgzQoivuwSU9274K2sSU/XLw0GVhqozdvCmSs6fAI3Qh/MXAom0qJn9ACylt9cLV/Ws+czqpiGnksasC5viQlLlAfSErYOoYaguhXS8KVhFyylEa/oq6zpjaxANpRKqsKN2YVUFQ38YM4L7Jd0t/1
    admin-user: AgBTGjkS4zdMpW1hv4xZsbkb2GAd4FX6jW3wWbXJGGmPtZhbbr31SIRky6JpYSGcxO3SKsK/XD9fn6v/LnGxBR1/ppSQfB5tYiSjtev/6woMdl1iwybIrq9id8e2wFWpUplazpv0gIKAtmto85M7K3ad9rmDxAuNr49w2jNynNemfkwZH/Lgvea5Oh6efHEdGTVlLgxMLTcWQ2ukbyF1JFQ58vrB8v1S4XduTaTb+y2k22CFDGdFamJXIRNyFqxwCVqHMkGREy6fFbYT2g90Bth6UebJidlbL1E+Acb1i8r5klii2ulK/W9AUMfnZ53CdOTgSnQpYg75KlXh3zw9T+tjgbbOOZ05bW1ofyVLY47nVXBGKN1JB16OEXS3wEMvn8ghPbmZeghghbKm3q8zG0BqoLwg/4cAPz+/WHHeQ7jXNMYCN3BRHQq70MKsO5Hxkr4bZ6D9X2JXe1/z4I7hdhAQ/SOGYnbAy0a2WcDEzFGKd1U5cF5qjyyUWzrnbJG9iqq46dyiLI9JC2NJFJbwdNyy37ZDpT3S5ze5W0Rj3NF5cWF/F1NteLuqOwk+m37oLfrxL1prbxHL1s/Ct1p0cR+b2uLqILqmAj2aJfOE5+Vq6w7cbqTKIPcJyISLhT3HpX5I0AYJLhw66WqlzbpY/3qTTNXWuT8T4iBQlvcQWgKufCA2ViIF0rRLBo1IB0EYnvNIxmGvxA==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
{{- end }}


