{
 "title": "Demo App Metrics",
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU Usage (rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"project-c\", pod=~\"demo-app.*\"}[1m])\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "HTTP Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"demo-app\"}[1m])",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Memory Usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"demo-app\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}